/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maintest.guiadmin;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import maintest.guiuser.LoginUser;
import maintest.mysql.Query;

/**
 *
 * @author YOGI DWI ANDRIAN
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin(String user) {
        initComponents();
        username.setText(user);
        retrieve();
    }

   
     //RETRIEVE BUTTON CLICKED
    private void retrieve()
    {
     String getCB = cb_kategori.getSelectedItem().toString();
     
     String i = "1";
            if (getCB.equals("Test IQ")) {
                 i = "1";
            }else if (getCB.equals("Psikotes")) {
                 i = "2";
            }else if (getCB.equals("Tes Logika")) {
                 i = "3";
            }else{
                 i = "4";
            }
            
     DefaultTableModel dm = new Query().getData(i);

     table_1.setModel(dm);
     
    }
    
     private void history()
    {
            
     DefaultTableModel dm = new Query().getDataHistory();

     table_2.setModel(dm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb_kategori = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        jwb_A = new javax.swing.JTextField();
        jwb_B = new javax.swing.JTextField();
        jwb_C = new javax.swing.JTextField();
        jwb_D = new javax.swing.JTextField();
        cb_benar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        edt_soal = new javax.swing.JTextArea();
        panel_1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_1 = new javax.swing.JTable();
        panel_2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_2 = new javax.swing.JTable();
        btnDel = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnhistory = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        username1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Test IQ", "Psikotes", "Tes Logika", "Tes Pengetahuan Umum" }));
        cb_kategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kategoriActionPerformed(evt);
            }
        });
        jPanel1.add(cb_kategori);
        cb_kategori.setBounds(130, 95, 150, 20);

        btnEdit.setBorder(null);
        btnEdit.setContentAreaFilled(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);
        btnEdit.setBounds(300, 460, 70, 20);

        jwb_A.setBorder(null);
        jwb_A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jwb_A.setOpaque(false);
        jPanel1.add(jwb_A);
        jwb_A.setBounds(465, 380, 340, 20);

        jwb_B.setBorder(null);
        jwb_B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jwb_B.setOpaque(false);
        jPanel1.add(jwb_B);
        jwb_B.setBounds(465, 415, 340, 20);

        jwb_C.setBorder(null);
        jwb_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jwb_C.setOpaque(false);
        jwb_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jwb_CActionPerformed(evt);
            }
        });
        jPanel1.add(jwb_C);
        jwb_C.setBounds(465, 450, 340, 20);

        jwb_D.setBorder(null);
        jwb_D.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jwb_D.setOpaque(false);
        jPanel1.add(jwb_D);
        jwb_D.setBounds(465, 488, 340, 20);

        cb_benar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        cb_benar.setBorder(null);
        cb_benar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cb_benar);
        cb_benar.setBounds(100, 463, 90, 20);

        edt_soal.setColumns(20);
        edt_soal.setRows(5);
        edt_soal.setBorder(null);
        edt_soal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edt_soal.setOpaque(false);
        jScrollPane1.setViewportView(edt_soal);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 380, 340, 70);

        panel_1.setBackground(new java.awt.Color(255, 51, 51));

        table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_1);

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        jPanel1.add(panel_1);
        panel_1.setBounds(20, 120, 790, 250);

        panel_2.setBackground(new java.awt.Color(255, 51, 51));

        table_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_2);

        javax.swing.GroupLayout panel_2Layout = new javax.swing.GroupLayout(panel_2);
        panel_2.setLayout(panel_2Layout);
        panel_2Layout.setHorizontalGroup(
            panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        panel_2Layout.setVerticalGroup(
            panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        jPanel1.add(panel_2);
        panel_2.setBounds(20, 120, 790, 250);

        btnDel.setBorder(null);
        btnDel.setContentAreaFilled(false);
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel1.add(btnDel);
        btnDel.setBounds(210, 490, 70, 26);

        btnrefresh.setBorder(null);
        btnrefresh.setContentAreaFilled(false);
        btnrefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnrefresh);
        btnrefresh.setBounds(282, 90, 70, 26);

        btnAdd.setBorder(null);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(210, 460, 70, 20);

        btnClear.setBorder(null);
        btnClear.setContentAreaFilled(false);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(302, 490, 70, 20);

        btnhistory.setBorder(null);
        btnhistory.setContentAreaFilled(false);
        btnhistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnhistory);
        btnhistory.setBounds(730, 90, 70, 20);

        username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        username.setText("username");
        jPanel1.add(username);
        username.setBounds(80, 28, 60, 14);

        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(730, 10, 73, 23);

        username1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        username1.setText("Hi,");
        jPanel1.add(username1);
        username1.setBounds(65, 28, 20, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintest/asset/bg.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int index = table_1.getSelectedRow();
        
         if (index == -1) {
             JOptionPane.showMessageDialog(null, "Klik kolom yang akan di Update");
        }
         
        String id = table_1.getValueAt(index, 0).toString();
        String getCB = cb_benar.getSelectedItem().toString();
        
        if (new Query().update(id, edt_soal.getText(), jwb_A.getText(), jwb_B.getText(),jwb_C.getText(),jwb_D.getText(),getCB)) {
            JOptionPane.showMessageDialog(null, "Successfully Updated");

            //CLEAR TXT
            edt_soal.setText("");
            jwb_A.setText("");
            jwb_B.setText("");
            jwb_C.setText("");
            jwb_D.setText("");

            retrieve();
        } else {
            JOptionPane.showMessageDialog(null, "Not Updated");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        panel_1.setVisible(true);
        retrieve();
        
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnClear.setEnabled(true);
        btnDel.setEnabled(true);
        edt_soal.setEnabled(true);
        cb_benar.setEnabled(true);
        jwb_A.setEnabled(true);
        jwb_B.setEnabled(true);
        jwb_C.setEnabled(true);
        jwb_D.setEnabled(true);
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void jwb_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jwb_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jwb_CActionPerformed
    
    //ADD OR SAVE
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (edt_soal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Soal tidak bisa kosong");
        }else if(jwb_A.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jawaban A belum diisi");
        }else if(jwb_B.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jawaban B belum diisi");
        }else if(jwb_C.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jawaban C belum diisi");
        }else if(jwb_D.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jawaban D belum diisi");
        }else{
            String getCB = cb_benar.getSelectedItem().toString();
            String getCB_ktgri = cb_kategori.getSelectedItem().toString();
            
           String i = "1";
            if (getCB_ktgri.equals("Test IQ")) {
                 i = "1";
            }else if (getCB_ktgri.equals("Psikotes")) {
                 i = "2";
            }else if (getCB_ktgri.equals("Tes Logika")) {
                 i = "3";
            }else{
                 i = "4";
            }
            

                if (new Query().add(edt_soal.getText(), jwb_A.getText(), jwb_B.getText(),jwb_C.getText(),jwb_D.getText(),getCB, i)) {
                     JOptionPane.showMessageDialog(null, "Soal sukses ditambahkan");

                    //CLEAR TXT
                    edt_soal.setText("");
                    jwb_A.setText("");
                    jwb_B.setText("");
                    jwb_C.setText("");
                    jwb_D.setText("");

                    retrieve();
                } else {
                    JOptionPane.showMessageDialog(null, "Not Saved");
                }
        }
       
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int index = table_1.getSelectedRow();
        
         if (index == -1) {
             JOptionPane.showMessageDialog(null, "Klik kolom yang akan di hapus");
        }else{
         
            String[] options = {"Ya", "Tidak"}; 
        int answ = JOptionPane.showOptionDialog(null, "Yakin dihapus??", "Konfirmasi Hapus", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (answ == 0) {
            String id = table_1.getValueAt(index, 0).toString();

            if (new Query().delete(id)) {
                JOptionPane.showMessageDialog(null, "Deleted Updated");

                //CLEAR TXT
                edt_soal.setText("");
                jwb_A.setText("");
                jwb_B.setText("");
                jwb_C.setText("");
                jwb_D.setText("");

           retrieve();
            } else
            {
                JOptionPane.showMessageDialog(null, "Not Deleted");
            }

        }
         }
    }//GEN-LAST:event_btnDelActionPerformed

    private void table_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_1MouseClicked
        String soal = table_1.getValueAt(table_1.getSelectedRow(), 1).toString();
        String a = table_1.getValueAt(table_1.getSelectedRow(), 2).toString();
        String b = table_1.getValueAt(table_1.getSelectedRow(), 3).toString();
        String c = table_1.getValueAt(table_1.getSelectedRow(), 4).toString();
        String d = table_1.getValueAt(table_1.getSelectedRow(), 5).toString();
        edt_soal.setText(soal);
        jwb_A.setText(a);
        jwb_B.setText(b);
        jwb_C.setText(c);
        jwb_D.setText(d);
    }//GEN-LAST:event_table_1MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       edt_soal.setText("");
       jwb_A.setText("");
       jwb_B.setText("");
       jwb_C.setText("");
       jwb_D.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void cb_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kategoriActionPerformed

    }//GEN-LAST:event_cb_kategoriActionPerformed

    private void btnhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistoryActionPerformed
        // TODO add your handling code here:
        panel_1.setVisible(false);
        history();
        
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        btnClear.setEnabled(false);
        btnDel.setEnabled(false);
        edt_soal.setEnabled(false);
        cb_benar.setEnabled(false);
        jwb_A.setEnabled(false);
        jwb_B.setEnabled(false);
        jwb_C.setEnabled(false);
        jwb_D.setEnabled(false);
        
    }//GEN-LAST:event_btnhistoryActionPerformed

    private void table_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_2MouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginUser login = new LoginUser();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String username = null;
                new admin(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnhistory;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JComboBox<String> cb_benar;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JTextArea edt_soal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jwb_A;
    private javax.swing.JTextField jwb_B;
    private javax.swing.JTextField jwb_C;
    private javax.swing.JTextField jwb_D;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_2;
    private javax.swing.JTable table_1;
    private javax.swing.JTable table_2;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
