/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maintest.guiuser;

import maintest.Objek.Activity;
import maintest.mysql.Query;

/**
 *
 * @author arief
 */
public class HalamanBerhasil extends javax.swing.JFrame {

    /**
     * Creates new form HalamanBerhasil
     */
    public HalamanBerhasil() {
        initComponents();
        
        Activity user = new Activity();
        
        skorText.setText(Integer.toString(user.getSkor()));
        sisaText.setText(Integer.toString(user.getSisaDurasi()));
        
        Query.updateSkorDanSisa(user.getIdRank(), user.getSkor(), user.getSisaDurasi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        skorLabel = new javax.swing.JLabel();
        skorText = new javax.swing.JLabel();
        sisaLabel = new javax.swing.JLabel();
        sisaText = new javax.swing.JLabel();
        keHomeBtn = new javax.swing.JButton();
        kePilihanBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 62, 69));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        skorLabel.setFont(new java.awt.Font("Capriola", 0, 36)); // NOI18N
        skorLabel.setForeground(new java.awt.Color(216, 216, 216));
        skorLabel.setText("Skor anda");
        jPanel1.add(skorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        skorText.setFont(new java.awt.Font("Asap", 0, 96)); // NOI18N
        skorText.setForeground(new java.awt.Color(117, 227, 128));
        skorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skorText.setText("2155");
        jPanel1.add(skorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 130, 450, -1));

        sisaLabel.setFont(new java.awt.Font("Capriola", 0, 36)); // NOI18N
        sisaLabel.setForeground(new java.awt.Color(216, 216, 216));
        sisaLabel.setText("Sisa waktu");
        jPanel1.add(sisaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        sisaText.setFont(new java.awt.Font("Asap", 0, 96)); // NOI18N
        sisaText.setForeground(new java.awt.Color(117, 227, 128));
        sisaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sisaText.setText("2155 det");
        jPanel1.add(sisaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 510, -1));

        keHomeBtn.setBackground(new java.awt.Color(232, 234, 150));
        keHomeBtn.setFont(new java.awt.Font("Capriola", 0, 24)); // NOI18N
        keHomeBtn.setForeground(new java.awt.Color(55, 62, 69));
        keHomeBtn.setText("<- home");
        keHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keHomeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(keHomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 320, 60));

        kePilihanBtn.setBackground(new java.awt.Color(117, 227, 128));
        kePilihanBtn.setFont(new java.awt.Font("Capriola", 0, 24)); // NOI18N
        kePilihanBtn.setForeground(new java.awt.Color(55, 62, 69));
        kePilihanBtn.setText("<- pilihan");
        kePilihanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kePilihanBtnActionPerformed(evt);
            }
        });
        jPanel1.add(kePilihanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 320, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keHomeBtnActionPerformed
        this.setVisible(false);
        
        LoginUser loginUser = new LoginUser();
        loginUser.setResizable(false);
        loginUser.setVisible(true);
        loginUser.setLocationRelativeTo(null);
    }//GEN-LAST:event_keHomeBtnActionPerformed

    private void kePilihanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kePilihanBtnActionPerformed
       Activity user = new Activity();
        if(!user.isIQEnable() && !user.isLogikaEnable() && !user.isPsikotesEnable() && !user.isUmumEnable()){
            
//            try{
//                TimeUnit.SECONDS.sleep(1);
//            }catch(Exception e){
//                System.err.print(e);
//            }
            
            this.setVisible(false);
            
            
            
            
            LoginUser loginUser = new LoginUser();
            loginUser.setResizable(false);
            loginUser.setVisible(true);
            loginUser.setLocationRelativeTo(null);
        }
        else{
            this.setVisible(false);
        
            HalamanPilihan halamanPilihan = new HalamanPilihan();
            halamanPilihan.setResizable(false);
            halamanPilihan.setVisible(true);
            halamanPilihan.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_kePilihanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanBerhasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanBerhasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanBerhasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanBerhasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanBerhasil().setVisible(true);
            }
        });
    }
    
    public void setSkorAndSisa(String skor, String sisa){
        String sisaWaktu = sisa + " det";
        skorText.setText(skor);
        sisaText.setText(sisaWaktu);
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keHomeBtn;
    private javax.swing.JButton kePilihanBtn;
    private javax.swing.JLabel sisaLabel;
    private javax.swing.JLabel sisaText;
    private javax.swing.JLabel skorLabel;
    private javax.swing.JLabel skorText;
    // End of variables declaration//GEN-END:variables
}
