/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maintest.guiuser;

import javax.swing.JOptionPane;

import javax.swing.JLabel;

import javax.swing.table.DefaultTableCellRenderer;
import maintest.Objek.Activity;

import maintest.mysql.Query;
import maintest.guiuser.HalamanPilihan;
import maintest.guiadmin.LoginAdmin;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author arief
 */
public class LoginUser extends javax.swing.JFrame {

    /**
     * Creates new form LoginUser
     */
    public LoginUser() {
        initComponents();
        

        
        setTable();
        
        Activity user = new Activity();
        
        user.setIQEnable(true);
        user.setUmumEnable(true);
        user.setLogikaEnable(true);
        user.setPsikotesEnable(true);
        
        user.setSkorIQ(0);
        user.setSkorLogika(0);
        user.setSkorPsikotes(0);
        user.setSkorUmum(0);
        
        
        loadRank();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLeft = new javax.swing.JPanel();
        brainText = new javax.swing.JLabel();
        testText = new javax.swing.JLabel();
        testText1 = new javax.swing.JLabel();
        namaText = new javax.swing.JTextField();
        mulaiBtn = new javax.swing.JButton();
        keAdminBtn = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        trophyImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        testIQRank = new javax.swing.JTable();
        tesIQHeader = new javax.swing.JTable();
        tesIQPanel = new javax.swing.JPanel();
        tesIQText = new javax.swing.JLabel();
        testUmumRank = new javax.swing.JTable();
        testUmumHeader = new javax.swing.JTable();
        testUmumPanel = new javax.swing.JPanel();
        tesUmumLabel = new javax.swing.JLabel();
        testLogikaRank = new javax.swing.JTable();
        testLogikaHeader = new javax.swing.JTable();
        testLogikaPanel = new javax.swing.JPanel();
        tesLogikaLabel = new javax.swing.JLabel();
        psikotestRank = new javax.swing.JTable();
        psikotestHeader = new javax.swing.JTable();
        psikotestPanel = new javax.swing.JPanel();
        psikotesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgLeft.setBackground(new java.awt.Color(119, 227, 117));
        bgLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        bgLeft.setFont(new java.awt.Font("Capriola", 0, 24)); // NOI18N
        bgLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brainText.setFont(new java.awt.Font("Capriola", 0, 64)); // NOI18N
        brainText.setForeground(new java.awt.Color(55, 62, 69));
        brainText.setText("Brain");
        bgLeft.add(brainText, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 88, -1, -1));

        testText.setFont(new java.awt.Font("Capriola", 0, 30)); // NOI18N
        testText.setForeground(new java.awt.Color(55, 62, 69));
        testText.setText("Test");
        bgLeft.add(testText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        testText1.setFont(new java.awt.Font("Capriola", 0, 24)); // NOI18N
        testText1.setForeground(new java.awt.Color(55, 62, 69));
        testText1.setText("Masukkan nama");
        bgLeft.add(testText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        namaText.setBackground(new java.awt.Color(183, 244, 186));
        namaText.setFont(new java.awt.Font("Asap", 0, 18)); // NOI18N
        namaText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 62, 69), 2, true));
        namaText.setMargin(new java.awt.Insets(0, 10, 0, 0));
        bgLeft.add(namaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 294, 61));

        mulaiBtn.setBackground(new java.awt.Color(55, 62, 69));
        mulaiBtn.setFont(new java.awt.Font("Capriola", 0, 24)); // NOI18N
        mulaiBtn.setForeground(new java.awt.Color(255, 255, 255));
        mulaiBtn.setText("Mulai");
        mulaiBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 62, 69), 1, true));
        mulaiBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mulaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiBtnActionPerformed(evt);
            }
        });
        bgLeft.add(mulaiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 170, 61));

        keAdminBtn.setBackground(new java.awt.Color(119, 227, 117));
        keAdminBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        keAdminBtn.setBorderPainted(false);
        keAdminBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keAdminBtn.setFocusPainted(false);
        keAdminBtn.setFocusable(false);
        keAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keAdminBtnActionPerformed(evt);
            }
        });
        bgLeft.add(keAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnAdmin.setBackground(new java.awt.Color(119, 227, 117));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintest/asset/interface 1.png"))); // NOI18N
        btnAdmin.setBorderPainted(false);
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.setFocusPainted(false);
        btnAdmin.setFocusable(false);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        bgLeft.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        getContentPane().add(bgLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 700));

        jPanel1.setBackground(new java.awt.Color(55, 62, 69));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trophyImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintest/asset/trophy.png"))); // NOI18N
        trophyImg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(trophyImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 60, 70));

        jLabel1.setFont(new java.awt.Font("Asap", 1, 40)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("TOP 3");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        testIQRank.setAutoCreateRowSorter(true);
        testIQRank.setBackground(new java.awt.Color(227, 248, 146));
        testIQRank.setFont(new java.awt.Font("Asap", 0, 15)); // NOI18N
        testIQRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, "1 st"},
                {null, null, null, "2 nd"},
                {null, null, null, "3 rd"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testIQRank.setEnabled(false);
        testIQRank.setShowVerticalLines(false);
        jPanel1.add(testIQRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 460, -1));

        tesIQHeader.setAutoCreateRowSorter(true);
        tesIQHeader.setBackground(new java.awt.Color(205, 227, 117));
        tesIQHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tesIQHeader.setFont(new java.awt.Font("Capriola", 0, 13)); // NOI18N
        tesIQHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nama", "Skor", "Sisa waktu", "Rank"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tesIQHeader.setEnabled(false);
        tesIQHeader.setShowHorizontalLines(false);
        tesIQHeader.setShowVerticalLines(false);
        jPanel1.add(tesIQHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 460, -1));

        tesIQPanel.setBackground(new java.awt.Color(205, 227, 117));

        tesIQText.setFont(new java.awt.Font("Capriola", 0, 15)); // NOI18N
        tesIQText.setText("Test IQ");
        tesIQPanel.add(tesIQText);

        jPanel1.add(tesIQPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 460, 30));

        testUmumRank.setAutoCreateRowSorter(true);
        testUmumRank.setBackground(new java.awt.Color(138, 255, 150));
        testUmumRank.setFont(new java.awt.Font("Asap", 0, 15)); // NOI18N
        testUmumRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, "1 st"},
                {null, null, null, "2 nd"},
                {null, null, null, "3 rd"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testUmumRank.setEnabled(false);
        testUmumRank.setShowVerticalLines(false);
        jPanel1.add(testUmumRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 460, -1));

        testUmumHeader.setBackground(new java.awt.Color(117, 227, 128));
        testUmumHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        testUmumHeader.setFont(new java.awt.Font("Capriola", 0, 13)); // NOI18N
        testUmumHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nama", "Skor", "Sisa waktu", "Rank"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testUmumHeader.setEnabled(false);
        testUmumHeader.setShowHorizontalLines(false);
        testUmumHeader.setShowVerticalLines(false);
        jPanel1.add(testUmumHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 460, -1));

        testUmumPanel.setBackground(new java.awt.Color(117, 227, 128));

        tesUmumLabel.setFont(new java.awt.Font("Capriola", 0, 15)); // NOI18N
        tesUmumLabel.setText("Test Pengetahuan Umum");
        testUmumPanel.add(tesUmumLabel);

        jPanel1.add(testUmumPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 460, 30));

        testLogikaRank.setBackground(new java.awt.Color(250, 196, 132));
        testLogikaRank.setFont(new java.awt.Font("Asap", 0, 15)); // NOI18N
        testLogikaRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, "1 st"},
                {null, null, null, "2 nd"},
                {null, null, null, "3 rd"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testLogikaRank.setEnabled(false);
        testLogikaRank.setShowVerticalLines(false);
        jPanel1.add(testLogikaRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 460, -1));

        testLogikaHeader.setAutoCreateRowSorter(true);
        testLogikaHeader.setBackground(new java.awt.Color(227, 176, 117));
        testLogikaHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        testLogikaHeader.setFont(new java.awt.Font("Capriola", 0, 13)); // NOI18N
        testLogikaHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nama", "Skor", "Sisa waktu", "Rank"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testLogikaHeader.setEnabled(false);
        testLogikaHeader.setShowHorizontalLines(false);
        testLogikaHeader.setShowVerticalLines(false);
        jPanel1.add(testLogikaHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 460, -1));

        testLogikaPanel.setBackground(new java.awt.Color(227, 176, 117));

        tesLogikaLabel.setFont(new java.awt.Font("Capriola", 0, 15)); // NOI18N
        tesLogikaLabel.setText("Test Logika");
        testLogikaPanel.add(tesLogikaLabel);

        jPanel1.add(testLogikaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 460, 30));

        psikotestRank.setBackground(new java.awt.Color(144, 255, 228));
        psikotestRank.setFont(new java.awt.Font("Asap", 0, 15)); // NOI18N
        psikotestRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, "1 st"},
                {null, null, null, "2 nd"},
                {null, null, null, "3 rd"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        psikotestRank.setEnabled(false);
        psikotestRank.setShowVerticalLines(false);
        jPanel1.add(psikotestRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 460, -1));

        psikotestHeader.setAutoCreateRowSorter(true);
        psikotestHeader.setBackground(new java.awt.Color(117, 227, 201));
        psikotestHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        psikotestHeader.setFont(new java.awt.Font("Capriola", 0, 13)); // NOI18N
        psikotestHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nama", "Skor", "Sisa waktu", "Rank"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        psikotestHeader.setEnabled(false);
        psikotestHeader.setShowHorizontalLines(false);
        psikotestHeader.setShowVerticalLines(false);
        jPanel1.add(psikotestHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 460, -1));

        psikotestPanel.setBackground(new java.awt.Color(117, 227, 201));

        psikotesLabel.setFont(new java.awt.Font("Capriola", 0, 15)); // NOI18N
        psikotesLabel.setText("Psikotes");
        psikotestPanel.add(psikotesLabel);

        jPanel1.add(psikotestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 460, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 0, 594, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiBtnActionPerformed
        String nama = namaText.getText();
        
        if(nama.equals("")){
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else if(nama.length() < 6){
            JOptionPane.showMessageDialog(null, "Harus lebih dari 5 karakter", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            
            if(Query.mulaiTest(nama)){
               this.setVisible(false);
               
               HalamanPilihan halamanPilihan = new HalamanPilihan();
               halamanPilihan.setResizable(false);
               halamanPilihan.setVisible(true);
               halamanPilihan.setLocationRelativeTo(null);
            
               
            }
            
            
        }
    }//GEN-LAST:event_mulaiBtnActionPerformed

    private void keAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keAdminBtnActionPerformed
        this.setVisible(false);
        
        LoginAdmin loginAdmin = new LoginAdmin();
        loginAdmin.setResizable(false);
        loginAdmin.setVisible(true);
        loginAdmin.setLocationRelativeTo(null);
    }//GEN-LAST:event_keAdminBtnActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginAdmin login = new LoginAdmin();
        login.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUser().setVisible(true);
            }
        });
    }
    
    private void setTable(){
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        
        tesIQHeader.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        tesIQHeader.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        tesIQHeader.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        tesIQHeader.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        tesIQHeader.setRowHeight(30);
        
        testIQRank.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        testIQRank.setRowHeight(25);
        
        testUmumHeader.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        testUmumHeader.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        testUmumHeader.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        testUmumHeader.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        testUmumHeader.setRowHeight(30);
        
        testUmumRank.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        testUmumRank.setRowHeight(25);
        
        testLogikaHeader.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        testLogikaHeader.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        testLogikaHeader.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        testLogikaHeader.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        testLogikaHeader.setRowHeight(30);
        
        testLogikaRank.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        testLogikaRank.setRowHeight(25);
        
        psikotestHeader.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        psikotestHeader.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        psikotestHeader.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        psikotestHeader.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        psikotestHeader.setRowHeight(30);
        
        psikotestRank.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        psikotestRank.setRowHeight(25);
    }
    
    private void loadRank(){
        String[] rank = {"1 st", "2 nd", "3 rd"};
        
        try{
        
            ResultSet rs = Query.getTopRank(1);
            
            
            
            DefaultTableModel modelIQ = new DefaultTableModel();

            modelIQ.addColumn("Nama");
            modelIQ.addColumn("Skor");
            modelIQ.addColumn("Sisa Waktu");
            modelIQ.addColumn("Rank");

            
            int i = 0;
            while(rs.next()){
                modelIQ.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rank[i++]});
            }
            
            testIQRank.setModel(modelIQ);
            
            rs = Query.getTopRank(2);
            
            DefaultTableModel modelPsikotes = new DefaultTableModel();

            modelPsikotes.addColumn("Nama");
            modelPsikotes.addColumn("Skor");
            modelPsikotes.addColumn("Sisa Waktu");
            modelPsikotes.addColumn("Rank");
            
            i = 0;
            while(rs.next()){
                modelPsikotes.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rank[i++]});
            }
            
           psikotestRank.setModel(modelPsikotes);
           
           rs = Query.getTopRank(3);
            
            DefaultTableModel modelLogika = new DefaultTableModel();

            modelLogika.addColumn("Nama");
            modelLogika.addColumn("Skor");
            modelLogika.addColumn("Sisa Waktu");
            modelLogika.addColumn("Rank");
            
            i = 0;
            while(rs.next()){
                modelLogika.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rank[i++]});
            }
            
           testLogikaRank.setModel(modelLogika);
           
           rs = Query.getTopRank(4);
            
            DefaultTableModel modelUmum = new DefaultTableModel();

            modelUmum.addColumn("Nama");
            modelUmum.addColumn("Skor");
            modelUmum.addColumn("Sisa Waktu");
            modelUmum.addColumn("Rank");
            
            i = 0;
            while(rs.next()){
                modelUmum.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rank[i++]});
            }
            
           testUmumRank.setModel(modelUmum);
           
           
            
        
        }catch(SQLException e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgLeft;
    private javax.swing.JLabel brainText;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keAdminBtn;
    private javax.swing.JButton mulaiBtn;
    private javax.swing.JTextField namaText;
    private javax.swing.JLabel psikotesLabel;
    private javax.swing.JTable psikotestHeader;
    private javax.swing.JPanel psikotestPanel;
    private javax.swing.JTable psikotestRank;
    private javax.swing.JTable tesIQHeader;
    private javax.swing.JPanel tesIQPanel;
    private javax.swing.JLabel tesIQText;
    private javax.swing.JLabel tesLogikaLabel;
    private javax.swing.JLabel tesUmumLabel;
    private javax.swing.JTable testIQRank;
    private javax.swing.JTable testLogikaHeader;
    private javax.swing.JPanel testLogikaPanel;
    private javax.swing.JTable testLogikaRank;
    private javax.swing.JLabel testText;
    private javax.swing.JLabel testText1;
    private javax.swing.JTable testUmumHeader;
    private javax.swing.JPanel testUmumPanel;
    private javax.swing.JTable testUmumRank;
    private javax.swing.JLabel trophyImg;
    // End of variables declaration//GEN-END:variables
}



